const configurations = [
  {
    id: 1,
    name: "Select Configuration",
    onlineTrains: 1,
    standbyUnits: 0,
    totalUnits: 1,
    maxOfflineBW:2,
    modules: 10,
    racksPerUnit: 2,
    modulesPerUnit: 1,
    onlineModules: 0,
    totalModules:2,
  },

  {
    id: 2,
    name: "Online Units",
    onlineTrains: 0,
    standbyUnits: 1,
    totalUnits: 2,
    maxOfflineBW: 8,
    modules: 2,
    racksPerUnit: 1,
    modulesPerUnit: 0,
    onlineModules: 2,
    totalModules: 9,
  },

  {
    id: 3,
    name: "Standby Units",
    onlineTrains: 8,
    standbyUnits: 3,
    totalUnits: 11,
    maxOfflineBW: 0,
    modules: 6,
    racksPerUnit: 2,
    modulesPerUnit: 2,
    onlineModules: 5,
    totalModules: 10,
  },

  {
    id: 4,
    name: "Total Units",
    onlineTrains: 12,
    standbyUnits: 4,
    totalUnits: 16,
    maxOfflineBW: 5,
    modules: 10,
    racksPerUnit: 2,
    modulesPerUnit: 5,
    onlineModules: 8,
    totalModules: 14,
  },

  {
    id: 5,
    name: "Max Offline BW/CEB",
    onlineTrains: 7,
    standbyUnits: 3,
    totalUnits: 10,
    maxOfflineBW: 4,
    modules: 5,
    racksPerUnit: 1,
    modulesPerUnit: 5,
    onlineModules: 4,
    totalModules: 9,
  },

  {
    id: 6,
    name: "Modules/Rack",
    onlineTrains: 6,
    standbyUnits: 2,
    totalUnits: 8,
    maxOfflineBW: 6,
    modules: 4,
    racksPerUnit: 1,
    modulesPerUnit: 4,
    onlineModules: 3,
    totalModules: 7,
  },

  {
    id: 7,
    name: "Racks/Unit",
    onlineTrains: 9,
    standbyUnits: 1,
    totalUnits: 10,
    maxOfflineBW:7,
    modules: 7,
    racksPerUnit: 2,
    modulesPerUnit: 3,
    onlineModules: 6,
    totalModules: 9,
  },

  {
    id: 8,
    name: "Modules/Unit",
    onlineTrains: 4,
    standbyUnits: 1,
    totalUnits: 5,
    maxOfflineBW:3,
    modules: 3,
    racksPerUnit: 1,
    modulesPerUnit: 3,
    onlineModules: 2,
    totalModules: 5,
  },

  {
    id: 9,
    name: "Online Modules",
    onlineTrains: 11,
    standbyUnits: 3,
    totalUnits: 14,
    maxOfflineBW: 0,
    modules: 9,
    racksPerUnit: 2,
    modulesPerUnit: 4,
    onlineModules: 7,
    totalModules: 13,
  },
  {
    id: 10,
    name: "Total Modules",
    onlineTrains: 11,
    standbyUnits: 3,
    totalUnits: 14,
    maxOfflineBW:2,
    modules: 9,
    racksPerUnit: 2,
    modulesPerUnit: 4,
    onlineModules: 7,
    totalModules: 13,
  },
];
export default configurations;