import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  data: {
    "method": "default",
    "exportReport": 0,
    "reportType": 3,
    "WaterTypeID": 5,
    "WaterSubTypeID": 51,
    "TechnologyId": 1,
    "Flow_Design": 100,
    "Flag_Design_Flow": 0,
    "Guideline_number": "51",
    "Temp_min": 10,
    "Temp_design": 25,
    "Temp_max": 40,
    "Recovery_Pretreat": 0.995,
    "Strainer_Size": 150,
    "Recovery_RO": "0",
    "Feed_acid_name": "0",
    "Feed_acid_conc": "0",
    "Feed_acid_pH": "7",
    "Feed_coag_name": "0",
    "Feed_coag_conc": "0",
    "Feed_ox_name": "0",
    "Feed_ox_conc": "0",
    "N_Part_number": "SFP-2860XP",
    "N_Part_number_long": "IntegraTec™ XP 51 IG",
    "Company": "DuPont",
    "Drinking_water_part_names": "FALSE",
    "IntegraPac": "FALSE",
    "T_Rack": "FALSE",
    "Mem_Rack": "FALSE",
    "IntegraFlo": "FALSE",
    "Flux_Filter_target": 50,
    "Flux_BW": 100,
    "Flux_CEB": 100,
    "Flow_FF": 2.55,
    "Flow_FF2": 0,
    "Flow_FF3": 0,
    "Flow_FF4": 0,
    "Flow_AS": 12,
    "Flow_AS2": 0,
    "Flow_mCIP_recycle": "0",
    "Flow_CIP_recycle": 1.5,
    "Flag_cycle_input": "0",
    "t_filtration_cycle": 20,
    "t_interval_AS": 20,
    "t_interval_CEB_acid": 36,
    "t_interval_CEB_caustic": 12,
    "t_interval_CEB_Oxidant": "0",
    "t_interval_mCIP": "0",
    "t_interval_CIP": 30,
    "t_MIT_module_day": 0,
    "TMP_slope_BW": 0,
    "TMP_slope_CEB1": 0,
    "TMP_slope_CEB2": 0,
    "TMP_slope_mCIP": "0",
    "TMP_slope_CIP": 0,
    "Standby_Option": "Constant operating flux, variable system output",
    "Flag_CIP_standby": 0,
    "Flag_Storage_Tank": 1,
    "N_Trains_online": 1,
    "N_Trains_standby": 0,
    "N_Trains_Redundant": 0,
    "N_Modules_per_Train": 1,
    "IP_Skids_train": 1,
    "IP_Mod_skid": 1,
    "Flag_BW": 1,
    "Flag_FF": 0,
    "Flag_BW_Protocol": 0,
    "Temp_BW": 25,
    "t_AS": 0.3333333333333333,
    "t_Drain": 0.5,
    "t_BW1": 0.5,
    "t_BW2": 0.5,
    "t_FF": 0.75,
    "t_LF": 0,
    "t_FTL": 0,
    "BW_ox_name": "0",
    "BW_ox_conc": 0,
    "Temp_CEB": 25,
    "Flag_CEB": 1,
    "t_AS_CEB": 0.3333333333333333,
    "t_Drain_CEB": 0.5,
    "t_BW1_CEB": 0.75,
    "t_BW2_CEB": 0.75,
    "t_FF_CEB": 0.75,
    "t_CEB_soak": 10,
    "t_BW1_CEBrinse": 0,
    "t_BW2_CEBrinse": 0,
    "N_CEB_RScycles": "1",
    "CEB1_acid_name": "0",
    "CEB1_acid_conc": 0,
    "CEB1_acid_pH": 0,
    "CEB1_org_acid_name": "0",
    "CEB1_org_acid_conc": 0,
    "Flag_CEB1_Chem": "false",
    "CEB2_base_name": "NaOH",
    "CEB2_base_conc": 0,
    "CEB2_base_pH": 12,
    "CEB2_ox_name": "NaOCl",
    "CEB2_ox_conc": 350,
    "Flag_CEB2_Chem": "false",
    "CEB3_ox_name": "0",
    "CEB3_ox_conc": "0",
    "Temp_mCIP": "0",
    "N_BW_mCIP": "0",
    "N_BW_Rinse_mCIP": "0",
    "Flag_mCIP": "0",
    "t_mCIP_heat": "0",
    "t_mCIP_recycle": "0",
    "t_mCIP_soak": "0",
    "N_mCIP_RScycles": "0",
    "mCIP_acid_name": "0",
    "mCIP_acid_conc": "0",
    "mCIP_acid_pH": "0",
    "mCIP_org_acid_name": "0",
    "mCIP_org_acid_conc": "0",
    "Flag_mCIP1_Chem": "false",
    "mCIP_base_name": "0",
    "mCIP_base_conc": "0",
    "mCIP_base_pH": "0",
    "mCIP_ox_name": "0",
    "mCIP_ox_conc": "0",
    "mCIP_SLS_name": "0",
    "mCIP_SLS_conc": "0",
    "Flag_mCIP2_Chem": "0",
    "Temp_CIP": 35,
    "N_BW_CIP": 2,
    "N_BW_Rinse_CIP": 1,
    "Flag_CIP": 1,
    "t_CIP_heat": 30,
    "t_CIP_recycle": 30,
    "t_CIP_soak": 90,
    "N_CIP_RScycles": 1,
    "CIP_acid_name": "0",
    "CIP_acid_conc": 0,
    "CIP_acid_pH": 0,
    "CIP_org_acid_name": "0",
    "CIP_org_acid_conc": 0,
    "CIP_N_Chem1_Flag": "false",
    "CIP_base_name": "NaOH",
    "CIP_base_conc": 0,
    "CIP_base_pH": 12,
    "CIP_ox_name": "NaOCl",
    "CIP_ox_conc": 2000,
    "CIP_SLS_name": "0",
    "CIP_SLS_conc": "0",
    "CIP_N_Chem2_Flag": "false",
    "AdditionalSettingsScreen": "false",
    "P_air_max": 0.75,
    "P_ADBW_max": 0,
    "P_Filtrate": 0.5,
    "Delta_P_piping_filtration": 0.4,
    "Delta_P_strainer_filtration": 0.1,
    "Delta_P_piping_BW": 0.5,
    "Delta_P_piping_mCIP": "0",
    "Delta_P_piping_CIP": 2.5,
    "StorageTankParameters": "0",
    "f_Chem_storage_days": 30,
    "f_BW_tank_feed": 0,
    "f_Filtrate_tank_safety_margin": 1,
    "f_BW_tank_safety_margin": 1,
    "f_mCIP_tank": "0",
    "f_CIP_tank": 2,
    "f_ADBW": 0,
    "f_FTL": 0,
    "N_valves_per_skid": 6,
    "t_wait": 0,
    "t_valve": 0.08333333333333333,
    "t_ramp": 0,
    "Power_PLC": 0.1,
    "Power_valve": 0,
    "ProjectLevelUserEntries": "0",
    "Eff_motor_feed": 0.92,
    "Eff_motor_BW": 0.92,
    "Eff_motor_mCIP": "0",
    "Eff_motor_CIP": 0.92,
    "Eff_motor_metering": 0.92,
    "Eff_motor_compressor": 0.92,
    "Eff_pump_feed": 0.8,
    "Eff_pump_BW": 0.8,
    "Eff_pump_mCIP": "0",
    "Eff_pump_CIP": 0.8,
    "Eff_pump_metering": 0.8,
    "Eff_compressor": 0.5,
    "OperatingCostPrices": "0",
    "Price_Elec": 0.09,
    "Price_Water": 0.14,
    "Price_Waste": 0.69,
    "N_BW_per_AS": "1",
    "N_F_per_CEB1": "93",
    "N_F_per_CEB2": "31",
    "N_F_per_CEB3": "0",
    "N_F_per_mCIP": "0",
    "N_F_per_CIP": "1860",
    "t_normal_module_cycle": "23.083333333333332",
    "N_Chem_CEB1": "1",
    "N_Chem_CEB2": "1",
    "N_Chem_CEB3": "1",
    "N_Chem_CIP": 2,
    "N_Chem_mCIP": "0",
    "ModuleProperties": "0",
    "Area_Module": 51,
    "Vol_module": 35,
    "Length_module": 1.86,
    "Length_fibers": 1.38,
    "N_capillary": 1,
    "N_Capillary_Ends": 1,
    "D_ID": 0.0007,
    "D_OD": 0.0013,
    "Av": 574.252445525702,
    "P0": 6.25,
    "S0": 0,
    "S10": 0,
    "S20": 0.05,
    "S30": 0.1,
    "S40": 0.2,
    "Feed_acid_bulk_conc": "0",
    "Feed_acid_density": "0",
    "Feed_acid_price": "0",
    "Feed_coag_bulk_conc": "0",
    "Feed_coag_density": "0",
    "Feed_coag_price": "0",
    "Feed_ox_bulk_conc": "0",
    "Feed_ox_density": "0",
    "Feed_ox_price": "0",
    "BW_ox_bulk_conc": 0,
    "BW_ox_density": 0,
    "BW_ox_price": 0,
    "CEB1_acid_bulk_conc": 0,
    "CEB1_acid_density": 0,
    "CEB1_acid_price": 0,
    "CEB1_org_acid_bulk_conc": 0,
    "CEB1_org_acid_density": 0,
    "CEB1_org_acid_price": 0,
    "CEB2_base_bulk_conc": 0.5,
    "CEB2_base_density": 1.5238,
    "CEB2_base_price": 0.258,
    "CEB2_ox_bulk_conc": 0.12,
    "CEB2_ox_density": 1.1364,
    "CEB2_ox_price": 0.33,
    "CEB3_ox_bulk_conc": 0,
    "CEB3_ox_density": 0,
    "CEB3_ox_price": 0,
    "mCIP_acid_bulk_conc": "0",
    "mCIP_acid_density": "0",
    "mCIP_acid_price": "0",
    "mCIP_org_acid_bulk_conc": "0",
    "mCIP_org_acid_density": "0",
    "mCIP_org_acid_price": "0",
    "mCIP_base_bulk_conc": "0",
    "mCIP_base_density": "0",
    "mCIP_base_price": "0",
    "mCIP_ox_bulk_conc": "0",
    "mCIP_ox_density": "0",
    "mCIP_ox_price": "0",
    "mCIP_SLS_bulk_conc": "0",
    "mCIP_SLS_density": "0",
    "mCIP_SLS_price": "0",
    "CIP_acid_bulk_conc": 0,
    "CIP_acid_density": 0,
    "CIP_acid_price": 0,
    "CIP_org_acid_bulk_conc": 0,
    "CIP_org_acid_density": 0,
    "CIP_org_acid_price": 0,
    "CIP_base_bulk_conc": 0.5,
    "CIP_base_density": 1.5238,
    "CIP_base_price": 0.258,
    "CIP_ox_bulk_conc": 0.12,
    "CIP_ox_density": 1.1364,
    "CIP_ox_price": 0.33,
    "CIP_SLS_bulk_conc": 0,
    "CIP_SLS_density": 0,
    "CIP_SLS_price": 0,
    "Citric_Acid_bulk_conc": 1,
    "FeCl3_bulk_conc": 1,
    "H2SO4_bulk_conc": 0.98,
    "HCl_bulk_conc": 0.32,
    "NaOCl_bulk_conc": 0.12,
    "NaOH_bulk_conc": 0.5,
    "Oxalic_Acid_bulk_conc": 1,
    "PACl_bulk_conc": 0,
    "SLS_bulk_conc": 0,
    "Citric_Acid_density": 1.665,
    "FeCl3_density": 2.898,
    "H2SO4_density": 1.8385,
    "HCl_density": 1.1604,
    "NaOCl_density": 1.1364,
    "NaOH_density": 1.5238,
    "Oxalic_Acid_density": 1.9,
    "PACl_density": 0,
    "SLS_density": 0,
    "Citric_Acid_price": 1.52,
    "FeCl3_price": 1.67,
    "H2SO4_price": 0.06,
    "HCl_price": 0.1,
    "NaOCl_price": 0.33,
    "NaOH_price": 0.258,
    "Oxalic_Acid_price": 0.94,
    "PACl_price": 0,
    "SLS_price": 0,
    "feed_water": {
        "designTemp": 25,
        "methodname": "normal",
        "ph": 7,
        "Degas": 0,
        "percentage_of_initial_total_CO2_remaining": 100,
        "Equilibrate_with": 0,
        "Adjustment_Type": 0,
        "Add_Reagent": 0,
        "Total_CO2": 0,
        "turbidity": 0,
        "organicToc": 0,
        "tss": 0,
        "tds": 1000.002296,
        "cations": [
            {
                "name": "Ba",
                "mgL": 0,
                "molCharge": 2,
                "soluteID": 7,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "Ca",
                "mgL": 0,
                "molCharge": 2,
                "soluteID": 5,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "K",
                "mgL": 0,
                "molCharge": 1,
                "soluteID": 2,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "Mg",
                "mgL": 0,
                "molCharge": 2,
                "soluteID": 4,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "Na",
                "mgL": 393.374685,
                "molCharge": 1,
                "soluteID": 3,
                "ppm": 856.287804,
                "meqL": 17.110835
            },
            {
                "name": "NH4",
                "mgL": 0,
                "molCharge": 1,
                "soluteID": 1,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "Sr",
                "mgL": 0,
                "molCharge": 2,
                "soluteID": 6,
                "ppm": 0,
                "meqL": 0
            }
        ],
        "anions": [
            {
                "name": "Br",
                "mgL": 0,
                "molCharge": -1,
                "soluteID": 28,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "Cl",
                "mgL": 606.625315,
                "molCharge": -1,
                "soluteID": 11,
                "ppm": 856.287804,
                "meqL": 17.110835
            },
            {
                "name": "CO3",
                "mgL": 0,
                "molCharge": -2,
                "soluteID": 8,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "F",
                "mgL": 0,
                "molCharge": -1,
                "soluteID": 12,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "HCO3",
                "mgL": 0,
                "molCharge": -1,
                "soluteID": 9,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "NO3",
                "mgL": 0,
                "molCharge": -1,
                "soluteID": 10,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "PO4",
                "mgL": 0,
                "molCharge": -3,
                "soluteID": 23,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "SO4",
                "mgL": 0,
                "molCharge": -2,
                "soluteID": 13,
                "ppm": 0,
                "meqL": 0
            }
        ],
        "neutrals": [
            {
                "name": "B",
                "mgL": 0,
                "molCharge": 0,
                "soluteID": 29,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "CO2",
                "mgL": 0,
                "molCharge": 0,
                "soluteID": 30,
                "ppm": 0,
                "meqL": 0
            },
            {
                "name": "SiO2",
                "mgL": 0,
                "molCharge": 0,
                "soluteID": 14,
                "ppm": 0,
                "meqL": 0
            }
        ],
        "LSI_targ": 0,
        "SDI_targ": 0,
        "ChemicalAdjustment": [
            {
                "CaSO4_per": 0,
                "BaSO4_per": 0,
                "SrSO4_per": 0,
                "CaF2_per": 0,
                "SiO2_per": 0,
                "MgOH2_per": 0,
                "LSI": 0,
                "SDI": 0
            }
        ]
    }
},
tabAvailableForUF:{
    FeedSetup:false,
    UF:false,
  },
};



export const ReportUFSlice = createSlice({
  name: "ReportUF",
  initialState,
  reducers: {
    UpdateUFReport: (state, action) => {
      state.data = action.payload;     
      localStorage.setItem("ReportUF", JSON.stringify(action.payload));
    },
    updateTabAvailableForUF: (state, action) => {
        state.tabAvailableForUF = action.payload;
    }
  },
});

// Action creators are generated for each case reducer function
export const { UpdateUFReport ,updateTabAvailableForUF } = ReportUFSlice.actions;

export default ReportUFSlice.reducer;